### PR TITLE
Implement gRPC Server

### PR DESCRIPTION
**Pull request by sseoreo**
Can I exclude some commits?
I want to push only "grpc/server/", not "grpc/ex-server".
The later is just a sample code.

### CODE REVIEW

**Comment by sseoreo** [comment]
Am i doing right to make a PR?

**Comment by hyunsube** [comment]
@sseoreo To exclude some commits, you need to use "git rebase" and push again!

**Comment by hyunsube** [comment]
Also, I think we need to organize folder architecture first. What I'm using now is as follows. There are app, mca, and model directory for each task.
```
./AI-LINUX-RUST
├── app
├── mca
│   ├── Cargo.lock
│   ├── Cargo.toml
│   ├── cbindgen.toml
│   ├── README.md
│   ├── src
│   │   ├── agent
│   │   │   ├── AgentHandler.rs
│   │   │   ├── main.rs
│   │   │   ├── ModelConnection.rs
│   │   │   ├── ModelEnum.rs
│   │   │   └── ModelStructure.rs
│   │   ├── api
│   │   │   ├── lib.rs
│   │   │   ├── mca_dbus.rs
│   │   │   ├── mca_operation.rs
│   │   │   └── mca.rs
│   │   └── common
│   │       └── Errors.rs
│   └── test.cpp
├── model
└── README.md
```

**Comment by sseoreo** [comment]
I think so, but where should I put rust server in mca?

**Pull request closed without merging**
